/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 -t public/models/pickles_3d_version_of_hyuna_lees_illustration-transformed.glb 
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pickles-3d-version-of-hyuna-lees-illustration-7b81fa2a3b33403fb47d451b24c78ffe
Title: "Pickles" 3d version of Hyuna Lee's illustration
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    ['floor.001']: THREE.MeshBasicMaterial
    ['cup_pickle__Base_Color.001']: THREE.MeshBasicMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://cdn.jsdelivr.net/gh/ebowwar/threejs-assets@main/pickles_3d_version_of_hyuna_lees_illustration-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['floor.001']} position={[0, -0.005, 0]} rotation={[0, 0.002, 0]} scale={0.109} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['cup_pickle__Base_Color.001']} position={[-0.023, 0.043, 0.021]} rotation={[-0.477, -0.168, 0.7]} scale={0.112} />
    </group>
  )
}

useGLTF.preload('https://cdn.jsdelivr.net/gh/ebowwar/threejs-assets@main/pickles_3d_version_of_hyuna_lees_illustration-transformed.glb')
